package com.spring.model;
// Generated Aug 30, 2020 8:42:35 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "demodb")
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -885857925650017818L;
	private Integer id;
	private String category;
	private Product product;

	public Category() {
	}

	public Category(String category) {
		this.category = category;
	}

	public Category(String category, Product product) {
		this.category = category;
		this.product = product;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "category", nullable = false, length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "category")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
